---
# tasks file for play2
- name: "get play release"
  shell: creates="{{ deploy_path }}/play-{{ play_version }}.zip"  cd {{ deploy_path }} &&  wget http://downloads.typesafe.com/play/{{ play_version }}/play-{{ play_version }}.zip
  tags: play

- name: "unzip play release"
  shell: creates="{{ deploy_path }}/play-{{ play_version }}/"  cd {{ deploy_path }} && unzip play-{{ play_version }}.zip
  tags: play

- name: add user for playframework
  user: name=playframework group=nogroup
  tags: play

- name: "configure play init.d"
  template: src=play.init.d.j2 dest=/etc/init.d/play mode=755
  tags: play

- name: "configure play run directory for pid"
  file: path=/var/run/play owner=playframework state=directory
  tags: play
